title: Visatouch Deeying
description: Personal Website
logo: logo.jpg
logo.alt: A figure depicting me in graduation gown with Megumi Katou Nendoroid.
show_downloads: false
theme: jekyll-theme-minimal
